import "./styles.css";
import { link } from "./refs/refs";
import "./components/popular";
import "./components/findFilms";
import "./components/animationToNav";
import "./components/loadMoreFilms";
import "./components/infoOfFilm";
import "./components/favoriteFilms";
import "./components/home";
import "./components/infoOfFavFilms";
import Swal from "sweetalert2/dist/sweetalert2.js";
import "sweetalert2/src/sweetalert2.scss";
import services from "./services";
